# kindly generated by appropriated Rails generator
Mailjet.configure do |config|
  config.api_key = '93094cbc03392c7418228465c283bd0f'
  config.secret_key = '41a80f4f855e6ce10eefca0dfa32ca48'
  config.default_from = 'adtechk@gmail.com'

end
